sudo: required
language: python
services:
- docker
env:
- distro=alpine
- distro=ubuntu
stages:
- test
- name: deploy
  if: branch = develop
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install --only-upgrade openssl curl
- sudo apt-get -y install docker-ce
- docker version
install: true
script:
- docker build --force-rm --pull --rm --tag salt-base:${distro} ${distro}/
- docker run --rm -it salt-base:${distro} uname -a
jobs:
  include:
  - stage: deploy
    env:
    - distro=all
    before_install: true
    script:
    - ".travis/deploy.sh"
branches:
  except:
  - master
notifications:
  slack:
    secure: H4qn/2ZlhezqGO2DODCtHszaPLylgSugRObMIveO2XJQBFqbk8EzPZ33rsPWl+lkkiWGwTefdKk0d+amkP8ri6WpB/1rkBf7G087vIBQndFjZlsDQ98igF6jmDfonIkBk1ISkLMO2FGEvkqHfldiE0FKyM0fyVhIK59cIHaUJ41wWH6BlmJ2o8w1GlN29ZHXuonuWibHfMwRZXb1nK/XT8J7h/tfq2WM2WADhihp39zloup7HU1fZ+DqphNuH5ebzjXOoC9tEjS9y4xRAJGAH98yqalJQIOJPglkEHaWigifH40WxyxYkYmNKBRVqgYBMgqcQPjAW9OehGHt5jhIGUis1RaIXtjljYWDux2VZrmbtxmS1/PDMvcT5nMRik49O6jX4Fxuo/kBj2WXWbTZUd4nzpT/mdqnzvzeY9vd/KHVjV+vrg+yRMoSk/83+YnfLZuc4In+1pdfQN5fPFqveM1iG7h1zT1CDmnO5Gl2tvNAO/jLCe7V9mQLJbwLqamx23zJ+JO2eiRW0XGhT07nhT91WU7VP4v6O2mrXYc0QB1sHgpFGeRkgMm/PF6LNPbIqUwjEgBkeSEHBjEPaHbiHk6opoIMDyXpnZTIWlOG58ZnvHRh1Kfd1XcXarquyGNoQevtfCcvnVf7ypNnotoJXHBKDnIJgN+oWVPcoxxZbo0=
  on_success: always
  on_failure: always
